version: '3.8'
services:
  backend:
    build:
      context: .
      args:
        BUILD_TARGET: backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://username:password@postgres:5432/dbname
    depends_on:
      - postgres
    volumes:
      - ./apps/backend:/usr/src/app

  frontend:
    build:
      context: .
      args:
        BUILD_TARGET: frontend
    ports:
      - '3001:3001'
    volumes:
      - ./apps/frontend:/usr/src/app

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
